<a href="https://colab.research.google.com/github/SaniyaIrfan1113/MachineLearningProjects/blob/main/02_Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Libraries


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

**Upload DataSet**

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving 50_Startups.csv to 50_Startups.csv


Read DataSet

In [ ]:
dataset = pd.read_csv("50_Startups.csv")

Understand DataSet

In [ ]:
dataset.shape

(50, 5)

In [ ]:
dataset.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [ ]:
dataset.describe()

,R&D Spend,Administration,Marketing Spend,Profit
count,50.000000,50.000000,50.000000,50.000000
mean,73721.615600,121344.639600,211025.097800,112012.639200
std,45902.256482,28017.802755,122290.310726,40306.180338
min,0.000000,51283.140000,0.000000,14681.400000
25%,39936.370000,103730.875000,129300.132500,90138.902500
50%,73051.080000,122699.795000,212716.240000,107978.190000
75%,101602.800000,144842.180000,299469.085000,139765.977500
max,165349.200000,182645.560000,471784.100000,192261.830000


In [ ]:
dataset.isnull().sum()

,0
R&D Spend,0
Administration,0
Marketing Spend,0
State,0
Profit,0


Separate Input and Output

In [ ]:
X = dataset.iloc[:, :-1].values


In [ ]:
Y = dataset.iloc[:, 4].values

In [ ]:
print(X[:5])
print(Y[:5])

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']]
[192261.83 191792.06 191050.39 182901.99 166187.94]


Handle Catagorical Data

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [ ]:
ct = ColumnTransformer(
    transformers=[
        ("encoder", OneHotEncoder(), [3])
    ],
    remainder="passthrough"
)

In [ ]:
X = np.array(ct.fit_transform(X))

In [ ]:
print(X[:5])

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]]


Split DataSet

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.20,
    random_state=0
)

In [ ]:
print(X_train.shape)
print(X_test.shape)

(40, 6)
(10, 6)


Create Model

In [ ]:
model = LinearRegression()

Train Model

In [ ]:
model.fit(X_train, Y_train)

LinearRegression()

Profit

=

f(
R&D Spend,
Administration,
Marketing Spend,
State
)

Predict

In [ ]:
Y_pred = model.predict(X_test)

In [ ]:
print(Y_pred)

[103015.20159795 132582.27760816 132447.73845175  71976.09851258
 178537.48221057 116161.24230167  67851.69209676  98791.73374687
 113969.43533014 167921.06569552]


In [ ]:
comparison = pd.DataFrame({
    "Actual":Y_test,
    "Predicted":Y_pred
})

comparison

,Actual,Predicted
0,103282.38,103015.201598
1,144259.40,132582.277608
2,146121.95,132447.738452
3,77798.83,71976.098513
4,191050.39,178537.482211
5,105008.31,116161.242302
6,81229.06,67851.692097
7,97483.56,98791.733747
8,110352.25,113969.435330
9,166187.94,167921.065696


In [ ]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [ ]:
print("MAE :",mean_absolute_error(Y_test,Y_pred))

print("MSE :",mean_squared_error(Y_test,Y_pred))

print("R2 Score :",r2_score(Y_test,Y_pred))

MAE : 7514.29365964318
MSE : 83502864.03256194
R2 Score : 0.9347068473282546


In [ ]:
print(model.coef_)

[ 8.66383692e+01 -8.72645791e+02  7.86007422e+02  7.73467193e-01
  3.28845975e-02  3.66100259e-02]


In [ ]:
print(model.intercept_)

42467.52924853278


Save Model

In [ ]:
import joblib

joblib.dump(model,"startup_profit_model.pkl")

['startup_profit_model.pkl']

In [ ]:
loaded_model = joblib.load("startup_profit_model.pkl")

02_Multiple_Linear_Regression.ipynb

1. Import Libraries
2. Upload Dataset
3. Read Dataset
4. Explore Dataset
5. Separate X and Y
6. Encode Categorical Data
7. Split Dataset
8. Train Model
9. Predict
10. Evaluate
11. Model Coefficients
12. Save Model