<a href="https://colab.research.google.com/github/SaniyaIrfan1113/MachineLearningProjects/blob/main/03_Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

Upload Dataset

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Social_Network_Ads.csv to Social_Network_Ads.csv


Read DataSet

Shape

In [ ]:
dataset = pd.read_csv("Social_Network_Ads.csv")

Information

In [ ]:
dataset.head()

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,19,19000,0
1,15810944,Male,35,20000,0
2,15668575,Female,26,43000,0
3,15603246,Female,27,57000,0
4,15804002,Male,19,76000,0


Understand Dataset

In [ ]:
dataset.shape

(400, 5)

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


Statistics

In [ ]:
dataset.describe()

,User ID,Age,EstimatedSalary,Purchased
count,4.000000e+02,400.000000,400.000000,400.000000
mean,1.569154e+07,37.655000,69742.500000,0.357500
std,7.165832e+04,10.482877,34096.960282,0.479864
min,1.556669e+07,18.000000,15000.000000,0.000000
25%,1.562676e+07,29.750000,43000.000000,0.000000
50%,1.569434e+07,37.000000,70000.000000,0.000000
75%,1.575036e+07,46.000000,88000.000000,1.000000
max,1.581524e+07,60.000000,150000.000000,1.000000


Missing Values

In [ ]:
dataset.isnull().sum()

,0
User ID,0
Gender,0
Age,0
EstimatedSalary,0
Purchased,0


Select Features and Target

In [ ]:
X = dataset.iloc[:, [2,3]].values

In [ ]:
Y = dataset.iloc[:,4].values

In [ ]:
print(X[:5])
print(Y[:5])

[[   19 19000]
 [   35 20000]
 [   26 43000]
 [   27 57000]
 [   19 76000]]
[0 0 0 0 0]


Split Dataset

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.25,
    random_state=0
)

In [ ]:
print(X_train.shape)
print(X_test.shape)

(300, 2)
(100, 2)


Feature Scaling

In [ ]:
sc = StandardScaler()

In [ ]:
X_train = sc.fit_transform(X_train)

In [ ]:
X_test = sc.transform(X_test)

In [ ]:
print(X_train[:5])

[[ 0.58164944 -0.88670699]
 [-0.60673761  1.46173768]
 [-0.01254409 -0.5677824 ]
 [-0.60673761  1.89663484]
 [ 1.37390747 -1.40858358]]


Create Model

In [ ]:
model = LogisticRegression()

Train Model

In [ ]:
model.fit(X_train, Y_train)

LogisticRegression()

Age + Estimated Salary

↓

Purchased (Yes/No)


Predict Test Data

In [ ]:
Y_pred = model.predict(X_test)

In [ ]:
print(Y_pred)

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0
 0 0 1 0 1 1 1 1 0 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 1]


Compare Actual vs Predicted

In [ ]:
comparison = pd.DataFrame({
    "Actual":Y_test,
    "Predicted":Y_pred
})

comparison

,Actual,Predicted
0,0,0
1,0,0
2,0,0
3,0,0
4,0,0
...,...,...
95,1,0
96,0,0
97,1,0
98,1,1


Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
cm = confusion_matrix(Y_test,Y_pred)

print(cm)

[[65  3]
 [ 8 24]]


Accuracy

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy = accuracy_score(Y_test,Y_pred)

print("Accuracy :",accuracy)

Accuracy : 0.89


Classification Report

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.89      0.96      0.92        68
           1       0.89      0.75      0.81        32

    accuracy                           0.89       100
   macro avg       0.89      0.85      0.87       100
weighted avg       0.89      0.89      0.89       100



Predict New Customer

In [ ]:
new_customer = sc.transform([[35,60000]])

In [ ]:
prediction = model.predict(new_customer)

print(prediction)

[0]


Probability Prediction

In [ ]:
model.predict_proba(new_customer)

array([[0.87030161, 0.12969839]])

Save Model

In [ ]:
import joblib

joblib.dump(model,"logistic_model.pkl")

['logistic_model.pkl']

In [ ]:
loaded_model = joblib.load("logistic_model.pkl")

03_Logistic_Regression.ipynb

1. Import Libraries
2. Upload Dataset
3. Read Dataset
4. Explore Dataset
5. Select Features
6. Split Dataset
7. Feature Scaling
8. Train Model
9. Prediction
10. Confusion Matrix
11. Accuracy
12. Classification Report
13. Predict New Customer
14. Save Model